---
title: "Lecture 1.3"
date: 2024-01-08

---

```{r}
library(tidyverse)
library(palmerpenguins)
```



```{r}
#untidy data
temp_data_wide <- tribble(
  ~date, ~station1, ~station2,  ~station3,
  "2023-10-01", 30.1, 29.8,  31.2,
  "2023-11-01", 28.6, 29.1,  33.4,
  "2023-12-01", 29.9, 28.5,  32.3
)
```



```{r}
#make data tidy

temp_data_long <- temp_data_wide %>% pivot_longer(cols = starts_with("station"), 
                                                  names_to = "station_id",
                                                  values_to = "temp_c")
```



## Plot 1 


```{r}

#mapping color globablly
ggplot(data = na.omit(penguins), 
       mapping = aes(y = bill_depth_mm ,
                     x = bill_length_mm ,
                     color = species)) +
  geom_point()+
  geom_smooth(method = "lm")+
  scale_color_manual(values = c("darkorange", "purple", "cyan4"))



## mapping color locally
ggplot(data = na.omit(penguins), 
       mapping = aes(y = bill_depth_mm ,
                     x = bill_length_mm)) +
  geom_point(aes(color = species))+
    geom_point(aes(color = species))+
  geom_smooth(method = "lm")


ggplot(penguins, aes(x = body_mass_g,
                     y = flipper_length_mm,
                     color = body_mass_g))+ 
  geom_point()+
  scale_color_gradient(low = "#132B43", high = "#F7DD4C")
  
```


## Plot 2
```{r}
ggplot(penguins, aes(x = species)) + 
  geom_bar()
```

Overriding Geom_bar's stat: 

```{r}
penguins_summary <- penguins %>% 
  count(species)

ggplot(penguins_summary, aes( x = species, y = n)) + 
  geom_bar(stat = "identity")
```


override default stat mapping

```{r}
ggplot(penguins, aes(x = species, y = after_stat(prop),
                     group = 1))+ 
  geom_bar()
```
position adjustments
```{r}


ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "stack") # you don't need to explicitly include `position = "stack"` since it's the default


```
```{r}
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "dodge")
```

```{r}
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = position_dodge2(preserve = "single"))
```

coordinates + themes
```{r}

ggplot(penguins, aes(x = species)) +
  geom_bar() +
  coord_cartesian() # you don't need to explicitly include `coord_cartesian()` since it's the default



ggplot(penguins, aes(x = species)) +
  geom_bar() +
  coord_flip() +
  theme_classic()+
  theme(axis.title = element_text(size = 17, color = "purple"))
```

